PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DROP TABLE "work_ocp_unit_type";
CREATE TABLE "work_ocp_unit_type" ("unit_type_id" integer NOT NULL PRIMARY KEY REFERENCES "general_unit_type" ("artwork_type_id"), "ocp_unit_id" integer NULL UNIQUE REFERENCES "valueaccounting_unit" ("id"), "unit_id" integer NULL UNIQUE REFERENCES "general_unit" ("id"));
INSERT INTO "work_ocp_unit_type" VALUES(34,NULL,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(35,7,11);
INSERT INTO "work_ocp_unit_type" VALUES(36,NULL,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(37,NULL,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(38,NULL,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(48,NULL,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(67,NULL,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(68,NULL,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(232,NULL,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(233,2,5);
INSERT INTO "work_ocp_unit_type" VALUES(234,3,8);
INSERT INTO "work_ocp_unit_type" VALUES(235,NULL,9);
INSERT INTO "work_ocp_unit_type" VALUES(236,4,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(237,1,7);
INSERT INTO "work_ocp_unit_type" VALUES(238,8,14);
INSERT INTO "work_ocp_unit_type" VALUES(240,5,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(241,NULL,1);
INSERT INTO "work_ocp_unit_type" VALUES(242,NULL,3);
INSERT INTO "work_ocp_unit_type" VALUES(243,NULL,4);
INSERT INTO "work_ocp_unit_type" VALUES(244,NULL,NULL);
INSERT INTO "work_ocp_unit_type" VALUES(245,NULL,15);
INSERT INTO "work_ocp_unit_type" VALUES(246,NULL,10);
INSERT INTO "work_ocp_unit_type" VALUES(247,NULL,12);
INSERT INTO "work_ocp_unit_type" VALUES(248,NULL,13);
INSERT INTO "work_ocp_unit_type" VALUES(249,NULL,2);
COMMIT;
