PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DROP TABLE "work_ocp_record_type";
CREATE TABLE "work_ocp_record_type" ("record_type_id" integer NOT NULL PRIMARY KEY REFERENCES "general_record_type" ("artwork_type_id"), "exchange_type_id" integer NULL UNIQUE REFERENCES "valueaccounting_exchangetype" ("id"), "ocp_artwork_type_id" integer NULL REFERENCES "work_ocp_artwork_type" ("artwork_type_id"));
INSERT INTO "work_ocp_record_type" VALUES(125,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(126,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(127,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(128,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(129,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(130,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(131,11,9);
INSERT INTO "work_ocp_record_type" VALUES(132,15,10);
INSERT INTO "work_ocp_record_type" VALUES(133,18,NULL);
INSERT INTO "work_ocp_record_type" VALUES(134,3,9);
INSERT INTO "work_ocp_record_type" VALUES(135,13,10);
INSERT INTO "work_ocp_record_type" VALUES(136,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(137,8,9);
INSERT INTO "work_ocp_record_type" VALUES(138,17,9);
INSERT INTO "work_ocp_record_type" VALUES(139,22,10);
INSERT INTO "work_ocp_record_type" VALUES(140,21,10);
INSERT INTO "work_ocp_record_type" VALUES(141,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(142,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(143,12,9);
INSERT INTO "work_ocp_record_type" VALUES(144,16,10);
INSERT INTO "work_ocp_record_type" VALUES(145,52,NULL);
INSERT INTO "work_ocp_record_type" VALUES(146,1,9);
INSERT INTO "work_ocp_record_type" VALUES(147,14,10);
INSERT INTO "work_ocp_record_type" VALUES(148,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(181,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(182,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(183,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(184,9,161);
INSERT INTO "work_ocp_record_type" VALUES(185,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(186,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(187,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(214,50,NULL);
INSERT INTO "work_ocp_record_type" VALUES(215,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(217,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(218,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(219,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(220,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(221,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(222,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(223,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(224,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(225,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(226,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(227,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(228,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(229,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(230,NULL,NULL);
INSERT INTO "work_ocp_record_type" VALUES(231,NULL,161);
CREATE INDEX "work_ocp_record_type_2b78a968" ON "work_ocp_record_type" ("ocp_artwork_type_id");
COMMIT;
