PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DROP TABLE "work_ocp_record_type";
CREATE TABLE "work_ocp_record_type" ("record_type_id" integer NOT NULL PRIMARY KEY REFERENCES "general_record_type" ("artwork_type_id"), "exchange_type_id" integer NULL REFERENCES "valueaccounting_exchangetype" ("id"));
INSERT INTO "work_ocp_record_type" VALUES(125,NULL);
INSERT INTO "work_ocp_record_type" VALUES(126,NULL);
INSERT INTO "work_ocp_record_type" VALUES(127,NULL);
INSERT INTO "work_ocp_record_type" VALUES(128,NULL);
INSERT INTO "work_ocp_record_type" VALUES(129,NULL);
INSERT INTO "work_ocp_record_type" VALUES(130,NULL);
INSERT INTO "work_ocp_record_type" VALUES(131,16);
INSERT INTO "work_ocp_record_type" VALUES(132,17);
INSERT INTO "work_ocp_record_type" VALUES(133,NULL);
INSERT INTO "work_ocp_record_type" VALUES(134,3);
INSERT INTO "work_ocp_record_type" VALUES(135,13);
INSERT INTO "work_ocp_record_type" VALUES(136,NULL);
INSERT INTO "work_ocp_record_type" VALUES(137,18);
INSERT INTO "work_ocp_record_type" VALUES(138,8);
INSERT INTO "work_ocp_record_type" VALUES(139,NULL);
INSERT INTO "work_ocp_record_type" VALUES(140,NULL);
INSERT INTO "work_ocp_record_type" VALUES(141,NULL);
INSERT INTO "work_ocp_record_type" VALUES(142,NULL);
INSERT INTO "work_ocp_record_type" VALUES(143,14);
INSERT INTO "work_ocp_record_type" VALUES(144,19);
INSERT INTO "work_ocp_record_type" VALUES(145,NULL);
INSERT INTO "work_ocp_record_type" VALUES(146,1);
INSERT INTO "work_ocp_record_type" VALUES(147,15);
INSERT INTO "work_ocp_record_type" VALUES(148,NULL);
DROP TABLE "work_ocp_material_type";
CREATE TABLE "work_ocp_material_type" ("material_type_id" integer NOT NULL PRIMARY KEY REFERENCES "general_material_type" ("artwork_type_id"), "facet_value_id" integer NULL UNIQUE REFERENCES "valueaccounting_facetvalue" ("id"), "resource_type_id" integer NULL UNIQUE REFERENCES "valueaccounting_economicresourcetype" ("id"));
INSERT INTO "work_ocp_material_type" VALUES(55,NULL,NULL);
INSERT INTO "work_ocp_material_type" VALUES(56,NULL,NULL);
INSERT INTO "work_ocp_material_type" VALUES(57,NULL,NULL);
INSERT INTO "work_ocp_material_type" VALUES(88,9,NULL);
INSERT INTO "work_ocp_material_type" VALUES(89,10,NULL);
INSERT INTO "work_ocp_material_type" VALUES(90,NULL,NULL);
INSERT INTO "work_ocp_material_type" VALUES(91,NULL,NULL);
INSERT INTO "work_ocp_material_type" VALUES(92,NULL,NULL);
INSERT INTO "work_ocp_material_type" VALUES(93,NULL,NULL);
INSERT INTO "work_ocp_material_type" VALUES(94,NULL,NULL);
INSERT INTO "work_ocp_material_type" VALUES(95,21,NULL);
INSERT INTO "work_ocp_material_type" VALUES(96,NULL,NULL);
INSERT INTO "work_ocp_material_type" VALUES(97,NULL,NULL);
INSERT INTO "work_ocp_material_type" VALUES(98,NULL,NULL);
DROP TABLE "work_ocp_nonmaterial_type";
CREATE TABLE "work_ocp_nonmaterial_type" ("nonmaterial_type_id" integer NOT NULL PRIMARY KEY REFERENCES "general_nonmaterial_type" ("artwork_type_id"), "facet_value_id" integer NULL UNIQUE REFERENCES "valueaccounting_facetvalue" ("id"), "resource_type_id" integer NULL UNIQUE REFERENCES "valueaccounting_economicresourcetype" ("id"));
INSERT INTO "work_ocp_nonmaterial_type" VALUES(49,17,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(50,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(51,22,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(52,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(53,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(54,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(65,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(71,19,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(72,NULL,51);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(73,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(74,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(75,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(76,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(77,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(78,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(79,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(80,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(81,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(82,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(83,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(84,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(85,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(86,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(87,NULL,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(149,16,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(150,23,NULL);
INSERT INTO "work_ocp_nonmaterial_type" VALUES(151,NULL,NULL);
CREATE INDEX "work_ocp_record_type_66601c4c" ON "work_ocp_record_type" ("exchange_type_id");
COMMIT;
