# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-11 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_ocp_artwork_type_unit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocp_artwork_type',
            old_name='artwork_type',
            new_name='ocpArtworkType_artwork_type',
        ),
        migrations.RenameField(
            model_name='ocp_artwork_type',
            old_name='material_type',
            new_name='ocpArtworkType_material_type',
        ),
        migrations.RenameField(
            model_name='ocp_artwork_type',
            old_name='nonmaterial_type',
            new_name='ocpArtworkType_nonmaterial_type',
        ),
        migrations.RenameField(
            model_name='ocp_artwork_type',
            old_name='unit_type',
            new_name='ocpArtworkType_unit_type',
        ),
        migrations.RenameField(
            model_name='ocp_record_type',
            old_name='ocp_artwork_type',
            new_name='ocpRecordType_ocp_artwork_type',
        ),
        migrations.RenameField(
            model_name='ocp_record_type',
            old_name='record_type',
            new_name='ocpRecordType_record_type',
        ),
        migrations.RenameField(
            model_name='ocp_unit_type',
            old_name='ocp_unit',
            new_name='ocpUnitType_ocp_unit',
        ),
        migrations.RenameField(
            model_name='ocp_unit_type',
            old_name='unit',
            new_name='ocpUnitType_unit',
        ),
        migrations.RenameField(
            model_name='ocp_unit_type',
            old_name='unit_type',
            new_name='ocpUnitType_unit_type',
        ),
    ]
