# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 07:05
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0028_auto_20170311_2054'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ocp_record_type',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ocp_unit_type',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
