# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0029_auto_20170510_0705'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ocp_record_type',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ocp_unit_type',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='fobi_data',
            field=models.OneToOneField(blank=True, help_text='this join request is linked to this custom form (fobi SavedFormDataEntry)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to='fobi_contrib_plugins_form_handlers_db_store.SavedFormDataEntry', verbose_name='custom fobi entry'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='requested_username',
            field=models.CharField(help_text='If you have already an account in OCP, you can put the same username.', max_length=32, verbose_name='Requested username'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='number_of_shares',
            field=models.IntegerField(default=1, help_text='How many shares would you like to underwrite? Each share is worth 30 Euros', verbose_name='Number of shares'),
        ),
    ]
