# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0012_auto_20170717_1841'),
        ('work', '0032_auto_20170705_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='exchange',
            field=models.OneToOneField(blank=True, help_text='this join request is linked to this Ocp Exchange', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to='valueaccounting.Exchange', verbose_name='exchange'),
        ),
    ]
