# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('valueaccounting', '0009_auto_20170422_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='FairpayOauth2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fairpay_user', models.CharField(editable=False, max_length=100)),
                ('access_token', models.CharField(editable=False, max_length=100)),
                ('refresh_token', models.CharField(editable=False, max_length=100)),
                ('expires_token', models.IntegerField(editable=False, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valueaccounting.EconomicAgent')),
            ],
        ),
    ]
