# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0009_auto_20170422_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicevent',
            name='digital_currency_tx_state',
            field=models.CharField(blank=True, choices=[(b'new', 'New'), (b'pending', 'Pending'), (b'broadcast', 'Broadcast'), (b'confirmed', 'Confirmed'), (b'external', 'External'), (b'error', 'Error')], max_length=12, null=True, verbose_name='digital currency transaction state'),
        ),
    ]
