# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 15:13
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0010_auto_20170530_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicresource',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='quantity'),
        ),
    ]
