# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0011_auto_20170609_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economicevent',
            name='digital_currency_tx_hash',
        ),
        migrations.RemoveField(
            model_name='economicevent',
            name='digital_currency_tx_state',
        ),
        migrations.RemoveField(
            model_name='economicresource',
            name='digital_currency_address',
        ),
    ]
