# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valueaccounting', '0012_auto_20170717_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='valueaccounting.Order', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='economicresourcetype',
            name='behavior',
            field=models.CharField(choices=[(b'work', 'Type of Work'), (b'account', 'Virtual Account'), (b'dig_curr', 'Digital Currency'), (b'dig_acct', 'Digital Currency Address'), (b'dig_wallet', 'Digital Currency Wallet'), (b'consumed', 'Produced/Changed + Consumed'), (b'used', 'Produced/Changed + Used'), (b'cited', 'Produced/Changed + Cited'), (b'produced', 'Produced/Changed only'), (b'other', 'Other')], default=b'other', max_length=12, verbose_name='behavior'),
        ),
    ]
