# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-11 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20161201_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbank',
            old_name='human',
            new_name='accBnk_human',
        ),
        migrations.RenameField(
            model_name='accountces',
            old_name='human',
            new_name='accCes_human',
        ),
        migrations.RenameField(
            model_name='accountcrypto',
            old_name='human',
            new_name='accCrypt_human',
        ),
        migrations.RenameField(
            model_name='address_type',
            old_name='space_type',
            new_name='addrTypeSpace_type',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='human',
            new_name='asset_human',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='material',
            new_name='asset_material',
        ),
        migrations.RenameField(
            model_name='company_type',
            old_name='being_type',
            new_name='companyType_being_type',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='nonmaterial',
            new_name='image_nonmaterial',
        ),
        migrations.RenameField(
            model_name='material_type',
            old_name='artwork_type',
            new_name='materialType_artwork_type',
        ),
        migrations.RenameField(
            model_name='nonmaterial_type',
            old_name='artwork_type',
            new_name='nonmaterialType_artwork_type',
        ),
        migrations.RenameField(
            model_name='project_type',
            old_name='being_type',
            new_name='projectType_being_type',
        ),
        migrations.RenameField(
            model_name='record_type',
            old_name='artwork_type',
            new_name='recordType_artwork_type',
        ),
        migrations.RenameField(
            model_name='region_type',
            old_name='space_type',
            new_name='regionType_space_type',
        ),
        migrations.RenameField(
            model_name='unit_type',
            old_name='artwork_type',
            new_name='unitType_artwork_type',
        ),
    ]
