# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('valueaccounting', '0011_auto_20170609_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaircoinAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(editable=False, max_length=96, verbose_name='faircoin address')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faircoin_address', to='valueaccounting.EconomicResource', verbose_name='resource')),
            ],
        ),
        migrations.CreateModel(
            name='FaircoinTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(blank=True, editable=False, max_length=96, null=True, verbose_name='faircoin transaction hash')),
                ('tx_state', models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('external', 'External'), ('error', 'Error')], max_length=12, null=True, verbose_name='faircoin transaction state')),
                ('to_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='to address')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faircoin_transaction', to='valueaccounting.EconomicEvent', verbose_name='event')),
            ],
        ),
    ]
