# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 16:15
from __future__ import unicode_literals

from django.db import migrations

def migrate_faircoin_addresses(apps, schema_editor):
    EconomicResource = apps.get_model('valueaccounting', 'EconomicResource')
    FaircoinAddress = apps.get_model('faircoin', 'FaircoinAddress')

    resources = EconomicResource.objects.filter(digital_currency_address__isnull=False)
    migrated_addresses = 0
    for resource in resources:
        fairaddress = FaircoinAddress(
            resource = resource,
            address = resource.digital_currency_address,
        )
        fairaddress.save()
        migrated_addresses += 1
    print('\n  Migrated addresses: ' + str(migrated_addresses))

def migrate_faircoin_transactions(apps, schema_editor):
    EconomicEvent = apps.get_model('valueaccounting', 'EconomicEvent')
    FaircoinTransaction = apps.get_model('faircoin', 'FaircoinTransaction')

    TX_STATE_CHOICES = ['new', 'pending', 'broadcast', 'confirmed', 'external', 'error']

    events = EconomicEvent.objects.filter(digital_currency_tx_state__isnull=False)
    migrated_transactions = 0
    for event in events:
        tx_state = event.digital_currency_tx_state
        if tx_state and tx_state in TX_STATE_CHOICES:
            fairtx = FaircoinTransaction(
                event = event,
                tx_state = tx_state,
                tx_hash = event.digital_currency_tx_hash,
                to_address = event.event_reference,
            )
            fairtx.save()
            migrated_transactions += 1
    print('  Migrated transactions: ' + str(migrated_transactions))


class Migration(migrations.Migration):

    dependencies = [
        ('faircoin', '0001_initial'),
        ('valueaccounting', '0011_auto_20170609_1513')
    ]

    operations = [
        migrations.RunPython(migrate_faircoin_addresses),
        migrations.RunPython(migrate_faircoin_transactions),
    ]
